stages:
  - lint
  - test
  - validate

variables:
  PYTHONPATH: "$CI_PROJECT_DIR"
  AIRFLOW_VERSION: "2.10.5"
  PYTHON_VERSION: "3.12"
  AIRFLOW_CONSTRAINT_URL: "https://raw.githubusercontent.com/apache/airflow/constraints-2.10.5/constraints-3.12.txt"

default:
  image: python:3.12-slim
  before_script:
    - python --version
    - pip install --upgrade pip

lint:
  stage: lint
  script:
    - pip install ruff==0.4.4
    - ruff check src tests dags

unit_tests:
  stage: test
  script:
    - pip install pytest==8.2.0 requests==2.31.0 python-dotenv==1.0.1
    - pip install pandas==2.2.2 numpy==1.26.4 pyarrow==15.0.2 scikit-learn==1.4.2 mlflow==2.13.0 "setuptools<82"
    - pip install google-cloud-bigquery==3.20.0 db-dtypes==1.2.0
    - pytest tests/test_ingestion.py tests/test_ml_training.py -v

dag_validation:
  stage: validate
  script:
    - pip install pytest==8.2.0
    - pip install "apache-airflow==$AIRFLOW_VERSION" --constraint "$AIRFLOW_CONSTRAINT_URL"
    - pip install python-dotenv==1.0.1 requests==2.31.0
    - pytest tests/test_airflow_dag.py -v